# QA pipeline at SonarSource
# Based on https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

RUN_ACTIVITY:
  - run-db-unit-tests-mysql56
  - run-db-unit-tests-mssql2012
  - run-db-unit-tests-mssql2014
  - run-db-unit-tests-oracle11g
  - run-db-unit-tests-oracle12c
  - run-db-unit-tests-postgresql93
  - run-db-integration-tests-mysql56-Category1
  - run-db-integration-tests-mysql56-Category2
  - run-db-integration-tests-mysql56-Category3
  - run-db-integration-tests-mysql56-Category4
  - run-db-integration-tests-mysql56-Category5
  - run-db-integration-tests-mysql56-Category6
  - run-db-integration-tests-mssql2014-Category1
  - run-db-integration-tests-mssql2014-Category2
  - run-db-integration-tests-mssql2014-Category3
  - run-db-integration-tests-mssql2014-Category4
  - run-db-integration-tests-mssql2014-Category5
  - run-db-integration-tests-mssql2014-Category6
  - run-db-integration-tests-oracle12c-Category1
  - run-db-integration-tests-oracle12c-Category2
  - run-db-integration-tests-oracle12c-Category3
  - run-db-integration-tests-oracle12c-Category4
  - run-db-integration-tests-oracle12c-Category5
  - run-db-integration-tests-oracle12c-Category6
  - run-db-integration-tests-postgresql93-Category1
  - run-db-integration-tests-postgresql93-Category2
  - run-db-integration-tests-postgresql93-Category3
  - run-db-integration-tests-postgresql93-Category4
  - run-db-integration-tests-postgresql93-Category5
  - run-db-integration-tests-postgresql93-Category6
  - run-upgrade-tests-mysql56
  - run-upgrade-tests-mssql2014
  - run-upgrade-tests-oracle12c
  - run-upgrade-tests-postgresql93
  - run-it-released-plugins
  - run-perf-tests

exclude:
  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2012
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-mssql2014
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-oracle11g
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-oracle12c
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-unit-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category5
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category6
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category5
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category6
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category5
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category6
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category1
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category2
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category3
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category4
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category5
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category6
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-mysql56
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-mssql2014
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-oracle12c
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-upgrade-tests-postgresql93
    SLAVE_TYPE: performance
  - RUN_ACTIVITY: run-it-released-plugins
    SLAVE_TYPE: performance

  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: dblinux

  - RUN_ACTIVITY: run-db-unit-tests-mysql56
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-mssql2012
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-mssql2014
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-oracle11g
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-oracle12c
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-unit-tests-postgresql93
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category1
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category2
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category3
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category4
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category5
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mysql56-Category6
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category1
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category2
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category3
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category4
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category5
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-mssql2014-Category6
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category1
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category2
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category3
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category4
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category5
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-oracle12c-Category6
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category1
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category2
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category3
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category4
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category5
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-db-integration-tests-postgresql93-Category6
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-upgrade-tests-mysql56
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-upgrade-tests-mssql2014
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-upgrade-tests-oracle12c
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-upgrade-tests-postgresql93
    SLAVE_TYPE: windows
  - RUN_ACTIVITY: run-perf-tests
    SLAVE_TYPE: windows
